name: Test Find Lowest Number

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-lowest-number:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Test Case 1 - Multiple numbers
      run: |
        python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
        diff test_data/test1_output.txt test_data/test1_expected.txt
    
    - name: Test Case 2 - Single number
      run: |
        python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
        diff test_data/test2_output.txt test_data/test2_expected.txt
    
    - name: Test Case 3 - Empty file
      run: |
        python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
        diff test_data/test3_output.txt test_data/test3_expected.txt